### PR TITLE
fix: prevent request on empty item array

### LINKED ISSUE #42: Fix empty ids for areDeleted
Error logs from dev:
```
"msg": "The post hook was registered at \n\tError\n    at GlobalTaskRunner.setTaskPostHookHandler 
(/home/node/app/dist/services/global-task-runner.js:281:39)\n    at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:94:12\n 
at Generator.next (<anonymous>)\n  
at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:27:71\n  
  at new Promise (<anonymous>)\n   
 at __awaiter (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:23:12)\n   
 at plugin (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:36:38)\n   
 at Plugin.exec (/home/node/app/node_modules/avvio/plugin.js:132:19)\n    
at Boot.loadPlugin (/home/node/app/node_modules/avvio/plugin.js:274:10)\n  
  at processTicksAndRejections (node:internal/process/task_queues:83:21)" } | {"level":50,"time":1674650779500,"pid":8,"hostname":"0.0.0.0","reqId":"req-1dt","msg":"The post hook was registered 
at \n\tError\n at GlobalTaskRunner.setTaskPostHookHandler (/home/node/app/dist/services/global-task-runner.js:281:39)\n at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:94:12\n
 at Generator.next (<anonymous>)\n
 at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:27:71\n 
at new Promise (<anonymous>)\n
 at __awaiter (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:23:12)\n
 at plugin (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:36:38)\n 
at Plugin.exec (/home/node/app/node_modules/avvio/plugin.js:132:19)\n 
at Boot.loadPlugin (/home/node/app/node_modules/avvio/plugin.js:274:10)\n 
at processTicksAndRejections (node:internal/process/task_queues:83:21)"}
```
```
  | 2023-01-25T13:46:19.500+01:00Copy{     "level": 50,     "time": 1674650779500,     "pid": 8,     "hostname": "0.0.0.0",    
 "reqId": "req-1dt",     "stack": "InvalidInputError: Value list must have at least 1 member.\n  
  at createListSqlFragment (/home/node/app/node_modules/slonik/dist/src/sqlFragmentFactories/createListSqlFragment.js:12:15)\n   
 at createSqlTokenSqlFragment (/home/node/app/node_modules/slonik/dist/src/factories/createSqlTokenSqlFragment.js:24:65)\n    
at Object.sql (/home/node/app/node_modules/slonik/dist/src/factories/createSqlTag.js:39:91)\n   
 at RecycledItemService.<anonymous> (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/db-service.js:95:37)\n   
 at Generator.next (<anonymous>)\n  
  at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/db-service.js:8:71\n   
 at new Promise (<anonymous>)\n    
at __awaiter (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/db-service.js:4:12)\n   
 at RecycledItemService.areDeleted (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/db-service.js:92:16)\n    at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:96:57\n   
 at Generator.next (<anonymous>)\n    
at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:27:71\n  
  at new Promise (<anonymous>)\n    at __awaiter (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:23:12)\n   
 at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:94:104\n   
 at GlobalTaskRunner.<anonymous> (/home/node/app/dist/services/global-task-runner.js:330:27)",     "type": "Error",     "msg": "Value list must have at least 1 member." } | {"level":50,"time":1674650779500,"pid":8,"hostname":"0.0.0.0","reqId":"req-1dt","stack":"InvalidInputError: Value list must have at least 1 member.\n at createListSqlFragment (/home/node/app/node_modules/slonik/dist/src/sqlFragmentFactories/createListSqlFragment.js:12:15)\n 
at createSqlTokenSqlFragment (/home/node/app/node_modules/slonik/dist/src/factories/createSqlTokenSqlFragment.js:24:65)\n 
at Object.sql (/home/node/app/node_modules/slonik/dist/src/factories/createSqlTag.js:39:91)\n 
at RecycledItemService.<anonymous> (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/db-service.js:95:37)\n at Generator.next (<anonymous>)\n 
at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/db-service.js:8:71\n at new Promise (<anonymous>)\n 
at __awaiter (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/db-service.js:4:12)\n 
at RecycledItemService.areDeleted (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/db-service.js:92:16)\n at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:96:57\n at Generator.next (<anonymous>)\n
 at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:27:71\n 
at new Promise (<anonymous>)\n 
at __awaiter (/home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:23:12)\n 
at /home/node/app/node_modules/graasp-plugin-recycle-bin/dist/plugin.js:94:104\n at GlobalTaskRunner.<anonymous> (/home/node/app/dist/services/global-task-runner.js:330:27)","type":"Error","msg":"Value list must have at least 1 member."}
```

This prevent `/with-categories` to work correctly.
I couldn't find the same log in prod, but the endpoint is even more broken @dialexo

### PR DESCRIPTION
**Pull request by pyphilia**
close #42

### CODE REVIEW

File: src/db-service.ts [hunk 1]
```diff
@@ -133,6 +133,10 @@ export class RecycledItemService {
     itemPaths: string[],
     transactionHandler: TrxHandler,
   ): Promise<Pick<Item, 'path'>[]> {
+    if (!itemPaths || !itemPaths.length) {
```
Comment (dialexo) [inline src/db-service.ts:136]: We may want to take the time to set [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks) to `true` in the tsconfig.json at some point to avoid those kinds of existence checks.

**Review by mochiruntime — APPROVED** [review]
LGTM :bear:
